apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: default
  labels:
    object: web-deployment
    name: web
    project: test 
spec:
  selector:
    matchLabels:
      object: web-pod
  template:
    metadata:
      labels:
        object: web-pod
        name: web
        project: test 
    spec:
      containers:
      - name: web-container
        image: arturakh/k8s:v3
        ports:
        - containerPort: 80
          name: http
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10 # ожидание перед первой проверкой
          periodSeconds: 5 # интервал между проверками
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"