apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: web-autoscaler
  namespace: default
  labels:
    object: web-hpa
    name: web
    project: test 
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web-deployment
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80