apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: default
  labels:
    object: web-service
    name: web
    project: test 
spec:
  selector:
    object: web-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
      nodePort: 30008
  type: NodePort   